# Fill here the Google Maps API keys for your application
#
# In this sample:
#
# For development and test, we have only one possible host (localhost:3000),
# so there is only a single key associated with the mode.
# development:
#  ABQIAAAAzMUFFnT9uH0xq39J0Y4kbhTJQa0g3IQ9GZqIMmInSLzwtGDKaBR6j135zrztfTGVOm2QlWnkaidDIQ
#
# In production, the app can be accessed through 2 different hosts:
# thepochisuperstarmegashow.com and example.com. There then needs a
# 2-key hash. If you deployed to one host, only the API key would be needed
# (as in development and test).

development:
 ABQIAAAAzMUFFnT9uH0xq39J0Y4kbhTJQa0g3IQ9GZqIMmInSLzwtGDKaBR6j135zrztfTGVOm2QlWnkaidDIQ

test:
 ABQIAAAAzMUFFnT9uH0xq39J0Y4kbhTJQa0g3IQ9GZqIMmInSLzwtGDKaBR6j135zrztfTGVOm2QlWnkaidDIQ

production:
 ABQIAAAAKnyBcabZuHxTDiLVF7UDYxTV6P4_ra9JcxGjiMCPDXPP5Z0oMxSXErTrbGKJHB_Y8x3olSHIEGOceA

# hjnews.cachevalleysearch.com: ABQIAAAAKnyBcabZuHxTDiLVF7UDYxRPk9mfgoMm-jGw2QDMxmV03rPOJxRyUwn9Ehf3EloAz06xN2-Py4hTzg
