# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 56) do

  create_table "asset2s", :force => true do |t|
    t.column "parent_id",     :integer
    t.column "type",          :string
    t.column "resource_type", :string
    t.column "resource_id",   :integer
    t.column "content_type",  :string
    t.column "filename",      :string
    t.column "thumbnail",     :string
    t.column "size",          :integer
    t.column "width",         :integer
    t.column "height",        :integer
  end

  create_table "assets", :force => true do |t|
    t.column "listing_id",    :integer
    t.column "image",         :string
    t.column "asset_type",    :string
    t.column "name",          :string
    t.column "caption",       :string
    t.column "created_on",    :datetime, :null => false
    t.column "updated_on",    :datetime, :null => false
    t.column "position",      :integer
    t.column "filename",      :string
    t.column "content_type",  :string
    t.column "size",          :integer
    t.column "width",         :integer
    t.column "height",        :integer
    t.column "parent_id",     :integer
    t.column "thumbnail",     :string
    t.column "special_id",    :integer
    t.column "resource_type", :string
    t.column "resource_id",   :integer
  end

  create_table "blogs", :force => true do |t|
    t.column "title",          :string
    t.column "abstract",       :string
    t.column "body",           :text
    t.column "date_published", :timestamp, :null => false
    t.column "created_at",     :timestamp, :null => false
    t.column "updated_at",     :timestamp, :null => false
  end

  create_table "captchas", :force => true do |t|
    t.column "code",       :integer,  :default => 0, :null => false
    t.column "created_on", :datetime,                :null => false
    t.column "failures",   :integer,  :default => 0, :null => false
  end

  create_table "categories", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
    t.column "code", :string
  end

  create_table "cities", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "closures", :force => true do |t|
    t.column "listing_id",  :integer
    t.column "closed_at",   :datetime
    t.column "title",       :string
    t.column "description", :text
    t.column "created_on",  :datetime, :null => false
    t.column "updated_on",  :datetime, :null => false
  end

  create_table "comments", :force => true do |t|
    t.column "user_id",    :integer,  :default => 0, :null => false
    t.column "listing_id", :integer,  :default => 0, :null => false
    t.column "body",       :text
    t.column "created_at", :datetime,                :null => false
  end

  create_table "friends", :force => true do |t|
    t.column "name",         :string
    t.column "email",        :string
    t.column "sender_name",  :string
    t.column "sender_email", :string
    t.column "created_on",   :datetime, :null => false
    t.column "special_id",   :integer
  end

  create_table "hits", :force => true do |t|
    t.column "listing_id", :integer
    t.column "visitor_id", :integer
    t.column "url",        :string
    t.column "created_at", :datetime, :null => false
    t.column "controller", :string
    t.column "action",     :string
    t.column "subaction",  :string
  end

  create_table "items", :force => true do |t|
    t.column "parent_id",     :integer
    t.column "type",          :string
    t.column "resource_type", :string
    t.column "resource_id",   :integer
    t.column "content_type",  :string
    t.column "filename",      :string
    t.column "thumbnail",     :string
    t.column "size",          :integer
    t.column "width",         :integer
    t.column "height",        :integer
    t.column "caption",       :string
  end

  create_table "listing_imports", :force => true do |t|
    t.column "business",   :string,  :default => "", :null => false
    t.column "address",    :string
    t.column "phone",      :string
    t.column "zip",        :string
    t.column "listing_id", :integer
    t.column "address2",   :string
    t.column "city",       :string
    t.column "state",      :string
    t.column "country",    :string
    t.column "email",      :string
    t.column "website",    :string
    t.column "phone2",     :string
    t.column "fax",        :string
    t.column "keywords",   :string
  end

  create_table "listings", :force => true do |t|
    t.column "category_id",       :integer
    t.column "user_id",           :integer,  :default => 0
    t.column "business",          :string,   :default => "", :null => false
    t.column "tagline",           :string
    t.column "address",           :string
    t.column "address2",          :string
    t.column "city",              :string
    t.column "state",             :string
    t.column "zip",               :string
    t.column "county",            :string
    t.column "email",             :string
    t.column "website",           :string
    t.column "phone",             :string
    t.column "fax",               :string
    t.column "phone2",            :string
    t.column "image",             :string
    t.column "active",            :integer,  :default => 0
    t.column "created_on",        :datetime,                 :null => false
    t.column "updated_on",        :datetime,                 :null => false
    t.column "about",             :text
    t.column "show_about",        :integer
    t.column "show_hours",        :integer
    t.column "show_menu",         :integer
    t.column "show_images",       :integer
    t.column "show_map",          :integer,  :default => 1
    t.column "show_services",     :integer,  :default => 0
    t.column "show_brochure",     :integer
    t.column "show_specials",     :integer,  :default => 0
    t.column "show_deluxe",       :integer,  :default => 0
    t.column "mon_hours",         :string
    t.column "tue_hours",         :string
    t.column "wed_hours",         :string
    t.column "thu_hours",         :string
    t.column "fri_hours",         :string
    t.column "sat_hours",         :string
    t.column "sun_hours",         :string
    t.column "hours_description", :string
    t.column "keywords",          :string
    t.column "editor_approved",   :integer,  :default => 0
    t.column "services",          :text
    t.column "paid",              :integer,  :default => 0
    t.column "date_paid_start",   :date
    t.column "date_paid_expires", :date
    t.column "max_images",        :integer
    t.column "max_brochures",     :integer
    t.column "max_menus",         :integer
    t.column "approver_id",       :integer
    t.column "approved_on",       :datetime
    t.column "imported_on",       :datetime
    t.column "featured",          :boolean
  end

  create_table "ratings", :force => true do |t|
    t.column "rating",        :integer,                :default => 0
    t.column "rateable_type", :string,   :limit => 15, :default => "", :null => false
    t.column "rateable_id",   :integer,                :default => 0,  :null => false
    t.column "user_id",       :integer,                :default => 0,  :null => false
    t.column "created_at",    :datetime,                               :null => false
  end

  add_index "ratings", ["user_id"], :name => "fk_ratings_user"

  create_table "specials", :force => true do |t|
    t.column "listing_id",     :integer
    t.column "title",          :string
    t.column "price_in_cents", :integer
    t.column "image",          :string
    t.column "description",    :text
    t.column "special_type",   :string
    t.column "date_active",    :date
    t.column "date_expires",   :date
    t.column "updated_on",     :datetime
    t.column "created_on",     :datetime
    t.column "featured",       :integer,  :default => 0
    t.column "price",          :string
  end

  create_table "users", :force => true do |t|
    t.column "listing_id",        :integer
    t.column "username",          :string
    t.column "password_salt",     :string
    t.column "password_hash",     :string
    t.column "name",              :string
    t.column "email",             :string
    t.column "is_active",         :integer
    t.column "is_admin",          :integer
    t.column "updated_on",        :datetime
    t.column "created_on",        :datetime
    t.column "login_on",          :datetime
    t.column "subscribed",        :string,   :default => "0"
    t.column "subscription_date", :datetime
    t.column "subscription_ip",   :string
  end

  create_table "visitors", :force => true do |t|
    t.column "ip",         :string
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime, :null => false
  end

end
